# Numpy

### Importando a biblioteca numpy

In [3]:
import numpy as np

In [4]:
lista = list(range(0,10))

In [5]:
print(lista)
print(len(lista))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10


In [6]:
lista2 = np.array(lista)

In [7]:
print(list(map(lambda valor : valor * 3 , lista2)))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [8]:
soma = lambda a,b : a+b

In [9]:
mult = lambda a,b : a*b

In [10]:
  def criaMatriz (num, num2) : 
        return list(map(lambda valor : list(range(valor, num2 + valor)) , range(0, num + 1)))

## Listas e Arrays - np.array(lista)

In [11]:
minha_lista = [1,2,3]

minha_lista = np.array(minha_lista)

print('{} é um array de uma dimenção'.format(minha_lista))

[1 2 3] é um array de uma dimenção


In [12]:
print(criaMatriz(3,5))

[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]


In [13]:
print('É uma Matriz de 2 dimentções')
print(np.array(criaMatriz(2,3))) 

É uma Matriz de 2 dimentções
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [14]:
print(np.array(criaMatriz(10,110)))

[[  0   1   2 ... 107 108 109]
 [  1   2   3 ... 108 109 110]
 [  2   3   4 ... 109 110 111]
 ...
 [  8   9  10 ... 115 116 117]
 [  9  10  11 ... 116 117 118]
 [ 10  11  12 ... 117 118 119]]


### Métodos de criação de arrays com Numpy

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.linspace(0,10,2)

array([ 0., 10.])

In [18]:
print('linspace cria arrays de um intervalo de valores, com N valores')

print(np.linspace(0, 10, 3))

linspace cria arrays de um intervalo de valores, com N valores
[ 0.  5. 10.]


### Criando Matrizes

#### Matrizes de ZEROS

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
arr = np.zeros(3)

print(arr)

[0. 0. 0.]


In [21]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Matrizes de UNS

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Matrizes Identidades (diagonal principal com 1)

In [24]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Biblioteca Random

cria um intervalo de valores aleatórios entre 0 e 1

In [25]:
np.random.rand(5)

array([0.54679005, 0.28175911, 0.60842506, 0.79856186, 0.81527112])

In [26]:
np.random.rand(5, 5) * 10

array([[1.33615882, 4.98920998, 2.42457677, 6.77808255, 5.22985079],
       [0.86002506, 9.79460183, 0.69841709, 9.8430458 , 1.7092806 ],
       [4.81423803, 6.26410756, 2.83873573, 5.2422528 , 6.50667121],
       [2.00601332, 1.59666574, 6.13713491, 0.48117252, 2.32402265],
       [0.65234347, 8.63676567, 0.16050371, 6.11829715, 9.52321448]])

Não precisa passar tuplas como paramentros, pode receber N paramentros para N dimensões da Matriz

In [27]:
np.random.rand(3,3,3) 

array([[[0.62705551, 0.21924183, 0.82156453],
        [0.73931082, 0.6915584 , 0.23886111],
        [0.02129528, 0.48350887, 0.92335094]],

       [[0.46243117, 0.72986702, 0.72211858],
        [0.49830205, 0.72527741, 0.77838219],
        [0.86957917, 0.01531011, 0.6594129 ]],

       [[0.05776496, 0.48793721, 0.43999631],
        [0.07316171, 0.96686425, 0.11085849],
        [0.82263352, 0.05156081, 0.30585954]]])

'

A função randn() cria numeros aleatórios não uniformes: média 0 e desvio padrão 1

In [28]:
np.random.randn(3,4)

array([[ 0.67481847,  0.17256064,  0.50878614,  0.71964233],
       [ 0.95898967,  0.9698979 ,  0.0960561 ,  0.10486126],
       [-0.27534565, -2.36564854,  0.21281953, -0.26613474]])

#### Random com numeros inteiros

In [29]:
np.random.randint(0, 100, 10)

array([59,  5, 34, 30, 98, 51,  0, 30, 26, 80])

In [30]:
np.round(
    np.random.rand(3,3) * 100
)

array([[ 1., 57., 20.],
       [85., 50.,  5.],
       [51., 86., 62.]])

In [31]:
np.round(np.random.randn(10,10) * 10)

array([[ 11.,  -5.,  31., -13.,  10.,  -9.,   9.,  -7.,  -2.,   2.],
       [ 18.,   0.,  13.,   3.,  -3.,  -8.,  -0.,   6.,  -6.,  -1.],
       [-16.,   5.,   5.,  -2.,  -6.,   9.,   9.,  -4.,  13.,   4.],
       [ -2.,   7.,  -8.,   2.,  -3., -14.,   1.,  13.,   4.,   4.],
       [  1.,  -6.,   5.,   5., -10.,  -5.,   2., -13., -12.,  -7.],
       [  4.,   8.,  -8.,   8.,   2.,   3.,  -4.,  12.,   8.,  -0.],
       [ -6.,  34.,  -1.,  -3., -18.,  -1., -10.,   6.,  -3., -10.],
       [ 24.,   9., -14., -13.,  -2.,  -6., -12., -14.,  17.,  -7.],
       [ -5.,  12.,   2.,   1.,  -1.,   9., -12.,   7.,  -8., -33.],
       [  0.,  -2., -10.,  -8.,  -4.,  -8., -10.,  11., -12., -16.]])

'
## Atributos e Métodos Numpy

In [32]:
arr = np.round(np.random.rand(25)*10)

print(arr)

[5. 5. 7. 8. 9. 2. 3. 6. 6. 9. 8. 8. 3. 3. 3. 1. 3. 8. 4. 2. 1. 1. 9. 6.
 8.]


In [33]:
arr.reshape(5,5)

array([[5., 5., 7., 8., 9.],
       [2., 3., 6., 6., 9.],
       [8., 8., 3., 3., 3.],
       [1., 3., 8., 4., 2.],
       [1., 1., 9., 6., 8.]])

In [34]:
arr = arr.reshape(5,5)

.shape é um atributo dos arrays, o tamanho das matrizes

In [35]:
arr.shape

(5, 5)

In [36]:
arr = np.round(np.random.rand(5,5,10)*10)

print(arr)

print(arr.shape)

[[[ 8.  4.  5.  5.  7. 10.  3.  8.  9.  5.]
  [ 6.  2.  2.  2.  1.  1.  6.  2.  7.  7.]
  [ 1.  1.  1.  6.  1.  6.  9.  7.  8.  5.]
  [ 8.  0.  1.  3.  5.  8.  7.  6.  5.  2.]
  [10.  1.  1.  3.  3.  8.  1.  3.  4.  7.]]

 [[ 1.  0.  9.  2. 10.  1.  1.  9.  8.  9.]
  [ 6.  8.  7.  5.  5.  2.  1.  1.  9.  3.]
  [ 2.  6.  6.  6.  6.  4.  6.  1.  8.  5.]
  [ 6.  4.  8.  5.  9.  3.  1.  5.  4.  0.]
  [ 4.  2.  4.  1.  6.  4.  1.  7.  3.  2.]]

 [[ 0.  3.  5.  6.  2.  1.  8.  2.  3.  5.]
  [ 7.  4.  9.  0.  7.  4.  5. 10.  1.  1.]
  [ 5.  2.  7.  0.  6.  7.  6.  3.  1.  5.]
  [ 5.  5.  6.  2.  4.  1.  8.  9.  8.  6.]
  [ 8.  7.  4.  7.  0.  8.  2.  5.  7.  9.]]

 [[ 2.  4.  3.  6.  2. 10.  1.  9.  5.  4.]
  [ 5.  6.  1.  1.  6.  8.  3.  1.  5.  8.]
  [ 7.  1.  1.  4.  0.  9.  1.  9. 10. 10.]
  [ 7.  5.  6.  1.  3.  1.  0.  3. 10.  5.]
  [ 1.  9.  0.  9.  4.  0.  1.  8.  7.  1.]]

 [[ 4.  4.  5.  3.  8.  8.  0.  0.  5.  2.]
  [ 2.  3.  7.  5.  7.  7.  9.  1.  9.  2.]
  [ 0.  0.  6.  7.  1.  

In [37]:
arr.max() #Maior elemento do array

10.0

In [38]:
arr.min() #menor elemento

0.0

In [39]:
arr.argmax() # posição do maior elemento

5

In [40]:
arr.argmin() # posição do maior elemento

31

'
'
# Fatiamentos e indexação de Arrays e Matrizes
'
'

In [61]:
base = np.round(np.random.rand(1,64)*10)

print(base)

[[ 7.  1.  3.  1.  8. 10.  7.  7.  3.  4.  7.  5.  6.  7.  3.  2.  6. 10.
   4.  7.  9.  4.  7.  2.  6.  9.  6.  8.  3.  4.  2.  1.  1.  9.  3.  5.
   7.  6.  7.  5.  3.  2.  6.  7.  5.  0.  2.  9.  4.  7. 10.  1.  9.  5.
   8.  5.  6.  0.  3.  1.  7.  8.  4.  1.]]


In [71]:
matriz = base[0][:16].reshape(4,4).copy()

In [72]:
matriz

array([[ 7.,  1.,  3.,  1.],
       [ 8., 10.,  7.,  7.],
       [ 3.,  4.,  7.,  5.],
       [ 6.,  7.,  3.,  2.]])

In [81]:
matriz[1][:]

array([ 8., 10.,  7.,  7.])

In [92]:
np.array(list(map(lambda array: array[1:2], matriz))).reshape(len(matriz),1)

array([[ 1.],
       [10.],
       [ 4.],
       [ 7.]])

In [90]:
matriz[2][3]

5.0

In [91]:
len(matriz)

4

In [100]:
matriz[2:4] = np.round(np.random.rand(2,4) * 1000)

In [101]:
print(matriz)

[[  7.   1.   3.   1.]
 [  8.  10.   7.   7.]
 [ 33. 451. 552. 909.]
 [ 84. 473. 353. 881.]]


In [103]:
np.array(list(map(lambda array: array[1:3], matriz))).reshape(len(matriz),2)

array([[  1.,   3.],
       [ 10.,   7.],
       [451., 552.],
       [473., 353.]])

In [104]:
matriz[:,1:3]

array([[  1.,   3.],
       [ 10.,   7.],
       [451., 552.],
       [473., 353.]])

In [105]:
matriz[:,0]

array([ 7.,  8., 33., 84.])

In [106]:
matriz[matriz > 500]

array([552., 909., 881.])

In [107]:
matriz[matriz < 100]

array([ 7.,  1.,  3.,  1.,  8., 10.,  7.,  7., 33., 84.])

In [112]:
len(matriz[matriz == 1])

2

In [119]:
matriz[1, 1]

10.0

'
'
# Operações entre Array e Matrizes

In [137]:
arrX = np.arange(0,12)

print(arrX)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [138]:
arrY = np.round(np.random.rand(1,12)*12)

print(arrY)

[[ 1. 12.  1.  8.  1. 10. 12. 10.  1.  5.  2.  0.]]


In [139]:
arrX + arrY

array([[ 1., 13.,  3., 11.,  5., 15., 18., 17.,  9., 14., 12., 11.]])

In [140]:
arrX - arrY

array([[ -1., -11.,   1.,  -5.,   3.,  -5.,  -6.,  -3.,   7.,   4.,   8.,
         11.]])

In [141]:
arrX * arrY

array([[ 0., 12.,  2., 24.,  4., 50., 72., 70.,  8., 45., 20.,  0.]])

In [142]:
arrX / arrY

<ipython-input-142-80d005a43451>:1: RuntimeWarning: divide by zero encountered in true_divide
  arrX / arrY


array([[0.        , 0.08333333, 2.        , 0.375     , 4.        ,
        0.5       , 0.5       , 0.7       , 8.        , 1.8       ,
        5.        ,        inf]])

In [145]:
arrY ** 2

array([[  1., 144.,   1.,  64.,   1., 100., 144., 100.,   1.,  25.,   4.,
          0.]])

### Agumas funções numpy .()

In [146]:
np.exp(arrY)  #Exponenciação

array([[2.71828183e+00, 1.62754791e+05, 2.71828183e+00, 2.98095799e+03,
        2.71828183e+00, 2.20264658e+04, 1.62754791e+05, 2.20264658e+04,
        2.71828183e+00, 1.48413159e+02, 7.38905610e+00, 1.00000000e+00]])

In [152]:
np.sqrt(arrY)   #Raiz Quadrada

array([[1.        , 3.46410162, 1.        , 2.82842712, 1.        ,
        3.16227766, 3.46410162, 3.16227766, 1.        , 2.23606798,
        1.41421356, 0.        ]])

In [153]:
np.sqrt(arrY ** 2)

array([[ 1., 12.,  1.,  8.,  1., 10., 12., 10.,  1.,  5.,  2.,  0.]])

In [154]:
np.sqrt(arrY)**2

array([[ 1., 12.,  1.,  8.,  1., 10., 12., 10.,  1.,  5.,  2.,  0.]])